language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

# See issue #812
group: deprecated-2017Q2

sudo: required
dist: trusty

cache:
  - pip

addons:
  postgresql: "9.3"
  apt:
    packages:
      - apache2
      - libapache2-mod-wsgi

branches:
  except:
    - none

env:
  - DB=sqlite
  - DB=postgres

install:
  # A dependency might use new pip syntax; upgrade to prevent breakage. See #771
  - pip install --upgrade pip
  - sh -e ci/apache/install.sh
  - sh -e ci/keystone/install.sh

script:
  - sh -e ci/pep8_tests.sh
  - sh -e ci/pylint_tests.sh
  - sh -e ci/no_trailing_whitespace.sh
  - sh -e ci/run_unit_tests.sh
  - sh -e ci/apache/run_integration_tests.sh
  - sh -e ci/keystone/run_integration_tests.sh
  - sh -e ci/deployment-mock-networks/run_integration_tests.sh
